ManagerTour/Models/Tours.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ManagerTour.Models
{
    public class Tours
    {
        private int _id;
        private int _user_id;
        private int _vehicle_id;
        private string _title;
        private string _description;
        private string _address_start;
        private string _address_end;
        private string _date_start;
        private string _date_end;
        private double _price_tour;
        private string _detail_price_tour;
        private int _amount_customer_maximum;
        private int _amount_customer_present;
        private int _status;
        private int _currentPage;
        private float _totalPage;
        private int _month;
        private int _count;
        private string _created_at;
        private string _updated_at;
        private int _minute;
        private User_information _user;
        private Vehicles _vehicles;
        private List<Vehicles> _listVehicle;
        private tour_picture _picture;

        public int Id { get => _id; set => _id = value; }
        public int User_id { get => _user_id; set => _user_id = value; }
        public int Vehicle_id { get => _vehicle_id; set => _vehicle_id = value; }

        [Required (ErrorMessage = "Tiêu đề không được để trống")]
        [StringLength(70,ErrorMessage = "Tiêu đề không vượt quá 70 ký tự")]
        public string Title { get => _title; set => _title = value; }

        [Required(ErrorMessage = "Mô tả tour không được để trống")]
        public string Description { get => _description; set => _description = value; }
        public string Address_start { get => _address_start; set => _address_start = value; }
        public string Address_end { get => _address_end; set => _address_end = value; }
        public string Date_start { get => _date_start; set => _date_start = value; }
        public string Date_end { get => _date_end; set => _date_end = value; }

        [Required(ErrorMessage = "Giá tour không được để trống")]
        [Range(1, double.MaxValue, ErrorMessage = "Giá tour nhỏ nhất là $1")]
        public double Price_tour { get => _price_tour; set => _price_tour = value; }

        [Required(ErrorMessage = "Chi tiết giá tour không được để trống")]
        public string Detail_price_tour { get => _detail_price_tour; set => _detail_price_tour = value; }

        [Required(ErrorMessage = "Số lượng khách hàng trong 1 tour không được để trống")]
        public int Amount_customer_maximum { get => _amount_customer_maximum; set => _amount_customer_maximum = value; }
        public int Amount_customer_present { get => _amount_customer_present; set => _amount_customer_present = value; }
        public int Status { get => _status; set => _status = value; }
        public string Created_at { get => _created_at; set => _created_at = value; }
        public string Updated_at { get => _updated_at; set => _updated_at = value; }
        public User_information User { get => _user; set => _user = value; }
        public Vehicles Vehicles { get => _vehicles; set => _vehicles = value; }
        public List<Vehicles> ListVehicle { get => _listVehicle; set => _listVehicle = value; }
        public float TotalPage { get => _totalPage; set => _totalPage = value; }
        public int CurrentPage { get => _currentPage; set => _currentPage = value; }
        public int Minute { get => _minute; set => _minute = value; }
        public int Month { get => _month; set => _month = value; }
        public int Count { get => _count; set => _count = value; }
        public tour_picture Picture { get => _picture; set => _picture = value; }
    }
}

ManagerTour/Controllers/TourController.cs
using ManagerTour.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Windows;

namespace ManagerTour.Controllers
{
    public class TourController : Controller
    {
        private List<Tours> _listTour;
        public List<Tours> ListTour { get => _listTour; set => _listTour = value; }

        private List<Vehicles> _listVehicle;
        public List<Vehicles> ListVehicle { get => _listVehicle; set => _listVehicle = value; }

        private List<tour_picture> _listPicture;
        public List<tour_picture> ListPicture { get => _listPicture; set => _listPicture = value; }

        //Pagination for table tour
        private int pageSize = 9;
        private int currentPage = 1;
        private float totalPage = 0;

        public TourController()
        {
            ListTour = new List<Tours>();
            ListVehicle = new List<Vehicles>();
            ListPicture = new List<tour_picture>();

            getVehicles();
            totalTour();
            ViewBag.ListTour = getTourPicture();
        }

        // GET: Tour
        public ActionResult Index(string keyword = null, string filter_status = "0")
        {
            if (Session["user"] != null)
            {
                try
                {

                    string query = "SELECT t.id, t.user_id, t.vehicle_id, t.title, t.description, t.address_start, t.address_end, t.date_start, t.date_end, " +
                                "t.price_tour, t.detail_price_tour, t.amount_customer_maximum, t.amount_customer_present, t.status, t.created_at, u.name as userName," +
                                " v.name as vehicleName, t.created_at, t.updated_at" +
                                " FROM tours as t join user_information as u on t.user_id = u.id join vehicles as v on t.vehicle_id = v.id";

                    if (!string.IsNullOrEmpty(filter_status) && !string.IsNullOrWhiteSpace(filter_status))
                    {
                        switch (filter_status)
                        {
                            case "1":
                                query += " WHERE t.status = 0";
                                break;
                            case "2":
                                query += " WHERE t.status = 1";
                                break;
                            case "3":
                                query += " WHERE t.status = 2";
                                break;
                            default:
                                query += " WHERE 1";
                                break;
                        }
                    }

                    //if keyword search exists perform search with field title or description of the tour
                    if (!string.IsNullOrEmpty(keyword) && !string.IsNullOrWhiteSpace(keyword))
                    {
                        query += " and title like '%" + keyword + "%' or description like '%" + keyword + "%'";
                    }

                    int totalRecords = (currentPage - 1) * pageSize;

                    query += " ORDER BY t.id LIMIT " + pageSize + " OFFSET " + totalRecords;


                    ConnectionMySQL connect = new ConnectionMySQL();
                    DataTable dt = new DataTable();
                    dt = connect.SelectData(query).Tables[0];

                    if (dt.Rows.Count > 0)
                    {
                        foreach (DataRow row in dt.Rows)
                        {
                            Tours tour = new Tours
                            {
                                Id = Int32.Parse(row["id"].ToString()),
                                User_id = Int32.Parse(row["user_id"].ToString()),
                                Vehicle_id = Int32.Parse(row["vehicle_id"].ToString()),
                                Title = row["title"].ToString(),
                                Description = row["description"].ToString(),
                                Address_start = row["address_start"].ToString(),
                                Address_end = row["address_end"].ToString(),
                                Date_start = String.Format("{0:yyyy-MM-dd}", row["date_start"]),
                                Date_end = String.Format("{0:yyyy-MM-dd}", row["date_end"]),
                                Price_tour = double.Parse(row["price_tour"].ToString()),
                                Detail_price_tour = row["detail_price_tour"].ToString(),
                                Amount_customer_maximum = Int32.Parse(row["amount_customer_maximum"].ToString()),
                                Amount_customer_present = Int32.Parse(row["amount_customer_present"].ToString()),
                                Status = Int32.Parse(row["status"].ToString()),
                                Created_at = String.Format("{0:dd-MM-yyyy}", row["created_at"].ToString()),
                                Updated_at = String.Format("{0:dd-MM-yyyy}", row["updated_at"].ToString()),
                                User = new User_information { Name = row["userName"].ToString() },
                                Vehicles = new Vehicles { Name = row["vehicleName"].ToString() },
                                TotalPage = totalPage,
                                CurrentPage = currentPage,
                            };

                            ListTour.Add(tour);
                        }
                    }

                    ViewBag.keyword = keyword;
                    ViewBag.filter_status = filter_status;

                    return View(ListTour);
                }
                catch
                {

                }
            }

            return RedirectToAction("Login", "Auth");
        }

        //get picture of the tour
        public List<tour_picture> getTourPicture()
        {
            try
            {
                string query = "SELECT * FROM `tour_picture` WHERE 1";
                ConnectionMySQL connect = new ConnectionMySQL();
                DataTable dt = new DataTable();
                dt = connect.SelectData(query).Tables[0];

                if (dt.Rows.Count > 0)
                {
                    foreach (DataRow row in dt.Rows)
                    {
                        tour_picture picture = new tour_picture()
                        {
                            Id = Int32.Parse(row["id"].ToString()),
                            Tour_id = Int32.Parse(row["tour_id"].ToString()),
                            Images = row["images"].ToString(),
                            Created_at = String.Format("{0:dd-MM-yyyy}", row["created_at"].ToString()),
                            Updated_at = String.Format("{0:dd-MM-yyyy}", row["updated_at"].ToString()),
                        };

                        ListPicture.Add(picture);
                    }
                }
            }
            catch { }

            return ListPicture;
        }

        //get view detail of the tour
        public ActionResult Detail(int id)
        {
            if (Session["user"] != null)
            {
                string query = "SELECT * FROM tours WHERE id = " + id;
                ConnectionMySQL connect = new ConnectionMySQL();
                DataTable dt = new DataTable();
                dt = connect.SelectData(query).Tables[0];

                if (dt.Rows.Count > 0)
                {
                    foreach (DataRow row in dt.Rows)
                    {
                        Tours tour = new Tours
                        {
                            Id = Int32.Parse(row["id"].ToString()),
                            User_id = Int32.Parse(row["user_id"].ToString()),
                            Vehicle_id = Int32.Parse(row["vehicle_id"].ToString()),
                            Title = row["title"].ToString(),
                            Description = row["description"].ToString(),
                            Address_start = row["address_start"].ToString(),
                            Address_end = row["address_end"].ToString(),
                            Date_start = String.Format("{0:yyyy-MM-dd}", row["date_start"]),
                            Date_end = String.Format("{0:yyyy-MM-dd}", row["date_end"]),
                            Price_tour = double.Parse(row["price_tour"].ToString()),
                            Detail_price_tour = row["detail_price_tour"].ToString(),
                            Amount_customer_maximum = Int32.Parse(row["amount_customer_maximum"].ToString()),
                            Amount_customer_present = Int32.Parse(row["amount_customer_present"].ToString()),
                            Status = Int32.Parse(row["status"].ToString()),
                            Created_at = String.Format("{0:dd-MM-yyyy}", row["created_at"].ToString()),
                            Updated_at = String.Format("{0:dd-MM-yyyy}", row["updated_at"].ToString()),
                            ListVehicle = ListVehicle,
                        };


                        ListTour.Add(tour);
                    }

                }

                return View(ListTour);
            }

            return RedirectToAction("Login", "Auth");
        }

        //get list Address
        public ActionResult getVehicles()
        {
            string query = "SELECT * FROM vehicles";

            ConnectionMySQL connect = new ConnectionMySQL();
            DataTable dt = new DataTable();
            dt = connect.SelectData(query).Tables[0];

            foreach (DataRow row in dt.Rows)
            {
                Vehicles vehicle = new Vehicles
                {
                    Id = Int32.Parse(row["id"].ToString()),
                    Name = row["name"].ToString(),
                };

                ListVehicle.Add(vehicle);
            }

            return View(ListVehicle);
        }


        //get total tour

ManagerTour/Views/Tour/Detail.cshtml
@model List<ManagerTour.Models.Tours>

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/Home.cshtml";
}


<link href="~/Content/css/detail_post.css" rel="stylesheet" />
<link href="~/Content/css/tour.css" rel="stylesheet" />

@using (Html.BeginForm("Update", "Tour", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="post_detail form_detail card border-0 tour_detail">
        <h1 class="text-center fw-bold h3 mb-3 pb-3">Detail Tour</h1>

        <input type="text" name="id" value="@Model[0].Id" hidden />

        <div class="mb-3">
            <label class="form-label">Title</label>
            @Html.TextBoxFor(m => Model[0].Title, new { @class = "form-control title_input shadow-non" })
            @Html.ValidationMessageFor(m => Model[0].Title)
        </div>

        <div class="mb-3">
            <label class="form-label">Description</label>
            @Html.TextAreaFor(m => Model[0].Description, new { rows = 10, @class = "form-control content_input shadow-none" })
            @Html.ValidationMessageFor(m => Model[0].Description)
        </div>

        <div class="d-flex mb-3">
            <div class="w-100 address_tour">
                <label class="form-label">Address Start</label>
                @Html.TextBoxFor(m => Model[0].Address_start, new { @class = "form-control content_input shadow-none", disabled = true })
                @Html.ValidationMessageFor(m => Model[0].Address_start)
            </div>

            <div class="w-100">
                <label class="form-label">Address End</label>
                @Html.TextBoxFor(m => Model[0].Address_end, new { @class = "form-control content_input shadow-none", disabled = true })
                @Html.ValidationMessageFor(m => Model[0].Address_end)
            </div>
        </div>

        <div class="d-flex mb-3">
            <div class="w-100 date_tour">
                <label class="form-label">Date Start</label>
                @Html.TextBoxFor(m => Model[0].Date_start, new { type = "datetime", @class = "form-control content_input shadow-none", disabled = true })
                @Html.ValidationMessageFor(m => Model[0].Date_start)
            </div>

            <div class="w-100">
                <label class="form-label">Date End</label>
                @Html.TextBoxFor(m => Model[0].Date_end, new { type = "datetime", @class = "form-control content_input shadow-none", disabled = true })
                @Html.ValidationMessageFor(m => Model[0].Date_end)
            </div>
        </div>

        <div class="mb-3">
            <label class="form-label">Price</label>
            @Html.TextBoxFor(m => Model[0].Price_tour, new { type = "number", @class = "form-control content_input shadow-none" })
            @Html.ValidationMessageFor(m => Model[0].Price_tour)
        </div>

        <div class="mb-3">
            <label class="form-label">Detail Price</label>
            @Html.TextAreaFor(m => Model[0].Detail_price_tour, new { rows = 4, @class = "form-control content_input shadow-none" })
            @Html.ValidationMessageFor(m => Model[0].Detail_price_tour)
        </div>

        <div class="mb-3">
            <label class="form-label">Amount</label>
            @Html.TextBoxFor(m => Model[0].Amount_customer_maximum, new { type = "number", @class = "form-control content_input shadow-none" })
            @Html.ValidationMessageFor(m => Model[0].Amount_customer_maximum)
        </div>

        <label class="form-label">Vehicle</label>
        <select class="form-select shadow-none mb-3" name="vehicle" disabled>
            @foreach (var vehicle in @Model[0].ListVehicle)
            {
                if (@Model[0].Vehicle_id == vehicle.Id)
                {
                    <option selected value="@vehicle.Id">@vehicle.Name</option>
                }
                else
                {
                    <option value="@vehicle.Id">@vehicle.Name</option>

                }
            }
        </select>

        <label class="form-label">Status</label>
        <div class="d-flex align-items-center mb-3">
            @if (Model[0].Status == 0)
            {
                <label for="cb_status_tour_0" class="rd_status_tour d-flex align-items-center">
                    <input type="radio" @(Model[0].Status == 0 ? "checked" : "") id="cb_status_tour_0" value="0" class="cb_status_tour" name="status_tour" />
                    Chờ duyệt
                </label>
            }


            <label for="cb_status_tour_1" class="rd_status_tour d-flex align-items-center">
                <input type="radio" @(Model[0].Status == 0 ? "disabled" : "") @(Model[0].Status == 1 ? "checked" : "") id="cb_status_tour_1" class="cb_status_tour" value="1" name="status_tour" />
                Hoạt động
            </label>

            <label for="cb_status_tour_2" class="rd_status_tour d-flex align-items-center">
                <input type="radio" @(Model[0].Status == 0 ? "disabled" : "") @(Model[0].Status == 2 ? "checked" : "") id="cb_status_tour_2" value="2" class="cb_status_tour" name="status_tour" />
                Tạm dừng
            </label>

        </div>

        <div class="d-flex justify-content-end">
            <a href="~/Tour/Index" class="cancel_update btn">Cancel</a>
            @if (@Model[0].Status == 0)
            {
                <a href="~/Tour/AgreeTour?id=@Model[0].Id" class="btn_agree btn">Agree</a>
            }
            <button type="submit" class="update_detail btn btn-dark">Update</button>
        </div>
    </div>
}

ManagerTour/Views/Tour/Index.cshtml
@model List<ManagerTour.Models.Tours>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Home.cshtml";
}

<link href="~/Content/css/post.css" rel="stylesheet" />
<link href="~/Content/css/tour.css" rel="stylesheet" />

<div class="breadcrumb d-flex justify-content-between align-items-center m-4">
    <div class="breadcrumb-item d-flex align-items-center">
        <h1>Dashboard</h1>

        <div class="text-break breadcrumb-item-text">
            <a>Tour</a> 
            <span> / </span>
            <span>Analytic</span>
        </div>
    </div>

</div>

<div class="posts tours">
    @using (@Html.BeginForm("Index", "Tour", FormMethod.Get))
    {
        <div class="d-flex justify-content-between align-items-center p-3 table-mobile">
            <div class="filter_city">
                <label class="form-label label_index">Status</label>
                <select class="form-select shadow-none user_select filter_status" name="filter_status">
                    <option selected value="0">Tất cả</option>
                    <option @(ViewBag.filter_status == "1" ? "selected" : "") value="1">Chờ duyệt</option>
                    <option @(ViewBag.filter_status == "2" ? "selected" : "") value="2">Hoạt động</option>
                    <option @(ViewBag.filter_status == "3" ? "selected" : "") value="3">Tạm dừng</option>
                </select>
            </div>

            <div class="">
                <label class="form-label label_index">Search</label>
                <div class="posts_search d-flex justify-content-center position-relative tour_search">
                    <input type="text" name="keyword" class="search_input border " value="@ViewBag.keyword" placeholder="Enter keyword search the tour..." />
                    <button id="btn_search" type="submit">
                        <i class="fa-solid fa-magnifying-glass"></i>
                    </button>
                </div>
            </div>
        </div>  

    }

    <table class="table tour_table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col" width="100px">User Name</th>
                <th scope="col" width="200px">Title</th>
                <th scope="col">Vehicle</th>
                <th scope="col">Description</th>
                <th scope="col" width="200px">Date</th>
                <th scope="col">Address</th>
                <th scope="col">Price</th>
                <th scope="col">Amount</th>
                <th scope="col" width="90px">Status</th>
                <th scope="col">Feature</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model)
            {
                <tr>
                    <td scope="row">@row.Id</td>
                    <td>@row.User.Name</td>
                    <td>
                        <p class="title">@row.Title</p>
                    </td>
                    <td>@row.Vehicles.Name</td>
                    <td>
                        <p class="content">@row.Description</p>
                    </td>
                    <td><p class="date fw-bold">@row.Date_start - @row.Date_end</p></td>
                    <td><p class="address_tour">@row.Address_start - @row.Address_end</p></td>
                    <td>$@row.Price_tour</td>
                    <td>
                        <p class="amount fw-bold">@row.Amount_customer_present / @row.Amount_customer_maximum</p>
                    </td>
                    <td>
                        @if (row.Status == 0)
                        {
                            <p class="status_tour fw-bold status_tour--agree">Chờ duyệt</p>
                        }
                        else if (row.Status == 1)
                        {
                            <p class="status_tour fw-bold status_tour--activity">Hoạt động</p>
                        }
                        else if (row.Status == 2)
                        {
                            <p class="status_tour fw-bold status_tour--drop">Tạm dừng</p>
                        }
                    </td>
                    <td>
                        <div class="user_function d-flex align-items-center">
                            <a class="detail" href="~/Tour/Detail?id=@row.Id">
                                <i class="fa-regular fa-pen-to-square"></i>
                            </a>

                            <input type="checkbox" class="cb_removePost" hidden id="cb_removePost_@row.Id" />
                            <label for="cb_removePost_@row.Id" class="lb_removePost position-fixed"></label>

                            <div class="card notify-remove-post position-fixed">
                                <div class="card-body">
                                    <h5 class="fw-bold">Are you want remove this tour ?</h5>
                                    <p>Choose <b>remove</b>, The tour will <b>remove forever</b></p>

                                    <div class="d-flex justify-content-end mt-3">
                                        <label for="cb_removePost_@row.Id" class="btn btn-notify-post cancel-remove-post d-flex align-items-center justify-content-center">Cancel</label>

                                        <a href="~/Tour/Delete?id=@row.Id" class="remove btn-notify-post btn btn-danger">
                                            Remove
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <label for="cb_removePost_@row.Id" class="remove">
                                <i class="fa-regular fa-trash-can"></i>
                            </label>
                        </div>
                    </td>
                </tr>
            }

        </tbody>
    </table>

    <div class="pagination d-flex justify-content-between p-2">
        <p class="pagination-page">
            Showing @if (Model.Count > 0)
            {@Model[0].CurrentPage}  to
            @if (Model.Count > 0)
            {@Model[0].TotalPage} of
            @if (Model.Count > 0)
            {@Model[0].TotalPage} entries
        </p>

        <div class="pagination-item d-flex">
            @using (Html.BeginForm("PreviousPage", "Tour", FormMethod.Get))
            {
                <button class="pagination-left pagination-arrow">
                    <i class="fa-solid fa-arrow-left"></i>
                </button>
            }

            @using (Html.BeginForm("NextPage", "Tour", FormMethod.Get))
            {
                <button class="pagination-right pagination-arrow">
                    <i class="fa-solid fa-arrow-right"></i>
                </button>
            }

        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.filter_status').change(function () {
            $(this).closest('form').submit();
        });

    });
</script>